# Test against this version of Node.js
environment:
  nodejs_version: "6.10.2"

# Install scripts. (runs after repo cloning)
install:
  # install node
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run benchmark

# Don't actually build.
build: off
